version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stack_ai_app
    restart: always
    ports:
      - "8018:8018"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5437
      POSTGRES_USER: charbel
      POSTGRES_PASSWORD: charbel
      POSTGRES_DB: stack_ai
      DATABASE_URL: postgresql://charbel:charbel@db:5437/stack_ai
    
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: charbel
      POSTGRES_PASSWORD: charbel
      POSTGRES_DB: stack_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U charbel -d stack_ai"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: charbeldaher34@gmail.com
      PGADMIN_DEFAULT_PASSWORD: charbel
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: